static const char* builtin_script = 
"function NumInputs()\n"
"{\n"
"    return inputs.length;\n"
"}\n"
"\n"
"function NumOutputs()\n"
"{\n"
"    return outputs.length;\n"
"}\n"
"\n"
"function GetInputName(c)\n"
"{\n"
"    return inputs[c];\n"
"}\n"
"\n"
"function GetOutputName(c)\n"
"{\n"
"    return outputs[c];\n"
"}\n";

